# Generated by Django 3.2.5 on 2021-11-26 12:35

import django.contrib.auth.base_user
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211122_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User.get_email_field_name),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.base_user.AbstractBaseUser.get_username),
        ),
    ]
