# Generated by Django 3.2.5 on 2021-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20211201_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='made',
            field=models.BooleanField(default=False),
        ),
    ]
