# Generated by Django 3.2.5 on 2021-12-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customer_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bags', 'Bags'), ('Bag straps', 'Bag straps'), ('Headbands', 'Headbands'), ('Headwraps', 'Headwraps'), ('Turban Hats', 'Turban Hats'), ('Dog harnesss', 'Dog harness'), ('Dog leash', 'Dog leash'), ('Other', 'Other')], default='Other', max_length=200, null=True),
        ),
    ]
